name: NewsBot (cada hora)

on:
  schedule:
    - cron: "0 * * * *"     # ejecuta cada hora (minuto 0) en UTC
  workflow_dispatch:        # permite lanzarlo manualmente

permissions:
  contents: write           # para commitear posted.db (estado)

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      WP_URL: ${{ secrets.WP_URL }}
      WP_USER: ${{ secrets.WP_USER }}
      WP_APP_PASSWORD: ${{ secrets.WP_APP_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # (Opcional) fija zona horaria solo para logs
      - name: TZ America/Santiago
        run: sudo timedatectl set-timezone America/Santiago

      - name: Ejecutar bot
        run: python automation_news.py

      # Mantener historial/rotación en Actions (commitea posted.db del runner)
      - name: Commit estado (posted.db)
        run: |
          git config user.name "newsbot-bot"
          git config user.email "newsbot-bot@users.noreply.github.com"
          git add -f posted.db
          git diff --cached --quiet || git commit -m "Update posted.db [ci skip]"
      - name: Push
        run: git push
